SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH(N'dbo.YangBan', N'GongChang') IS NULL
BEGIN
    ALTER TABLE dbo.YangBan ADD GongChang NVARCHAR(120) NULL;
END;

IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = N'dbo'
      AND TABLE_NAME = N'YangBan'
      AND COLUMN_NAME = N'GongChang'
      AND (DATA_TYPE <> N'nvarchar' OR CHARACTER_MAXIMUM_LENGTH < 120)
)
BEGIN
    ALTER TABLE dbo.YangBan ALTER COLUMN GongChang NVARCHAR(120) NULL;
END;

IF COL_LENGTH(N'dbo.YangBan', N'FuZeRen') IS NULL
BEGIN
    ALTER TABLE dbo.YangBan ADD FuZeRen NVARCHAR(80) NULL;
END;

IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = N'dbo'
      AND TABLE_NAME = N'YangBan'
      AND COLUMN_NAME = N'FuZeRen'
      AND (DATA_TYPE <> N'nvarchar' OR CHARACTER_MAXIMUM_LENGTH < 80)
)
BEGIN
    ALTER TABLE dbo.YangBan ALTER COLUMN FuZeRen NVARCHAR(80) NULL;
END;

COMMIT TRANSACTION;
